<a href="https://colab.research.google.com/github/kamaleshBK/kamal/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Python

## 1. Split this string

In [3]:
s = "Hi there Sam!"

In [4]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [14]:
planet = "Earth"
diameter = 12742


In [16]:
kamal = " The diameter of {} is {} kilometers.".format(planet,diameter)
kamal

' The diameter of Earth is 12742 kilometers.'

## 3. In this nest dictionary grab the word "hello"

In [19]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [21]:
d['k1'][3]['tricky'][3]['target'][3]


'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [25]:
import numpy as np
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
import numpy as np
arr = np.ones(10)*5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [30]:
import numpy as np
arr = np.arange(20,35,2)
arr

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [35]:
kamal = np.arange(9).reshape(3,3)
kamal

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [36]:
a = np.array([1,2,3])
b = np.array([4,5,6])
kamal1 = np.concatenate((a,b),axis=0)
kamal1

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [42]:
import pandas as pd


In [43]:
kam = pd.DataFrame(np.arange(6).reshape(3,2))
kam.index = ['A','B','C']
kam.column = ['1','2']
kam

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  This is separate from the ipykernel package so we can avoid doing imports until


0  1
A  0  1
B  2  3
C  4  5

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [44]:
thenna = pd.date_range(start="01-01-2023",end="10-02-2023")
thenna

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [45]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [46]:
thenna = pd.DataFrame(lists)
thenna

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24